### PR TITLE
Skynet

### PR DESCRIPTION
**Pull request by wittmer85**
:warning: Hasn't become self aware yet

@githubteacher  Could you turn on additional network connections....no reason...

### CODE REVIEW

**Comment by wittmer85** [comment]
He got axed in Terminator 2.  Wall-E completed the work after he got electrocuted by the auto-pilot

**Comment by jeffreyerikson** [comment]
Ah, got it . . . "founder" not "creator" :smile:

**Comment by wittmer85** [comment]
yes exactly!

**Comment by wittmer85** [comment]
@jeffreyerikson does this look good for merge

**Comment by jeffreyerikson** [comment]
:+1:

**Pull request merged**
