### PR TITLE
Begin adding Grace's bio

### PR DESCRIPTION
**Pull request by gaoyu01**
: work in progress. not ready to merger yet : warning:
This work is related to #30

### CODE REVIEW

**Comment by gaoyu01** [comment]
:warning:  work in progress. not ready to merger yet :warning:

**Comment by gaoyu01** [comment]
Ready to commit :ok:

**Comment by gaoyu01** [comment]
Ready to merge :+1:

**Comment by gaoyu01** [comment]
@githubteacher can you give me a :+1: before merge?

**Comment by glennon** [comment]
:+1: bio looks ready to merge

**Comment by gaoyu01** [comment]
@glennon  thanks :smile:

**Pull request merged**
