### PR TITLE
grodrigu bio ready to add

### PR DESCRIPTION
**Pull request by grodrigu**

### CODE REVIEW

**Comment by grodrigu** [comment]
Hi @githubteacher, please merge my bio into master

**Comment by arturom-uci** [comment]
@grodrigu good start. add more!!

**Comment by arturom-uci** [comment]
@grodrigu merge away sir!

**Comment by grodrigu** [comment]
:+1: Self-authorization of merge

**Comment by grodrigu** [comment]
Merged as part of issue #49

**Pull request merged**
